:toc: macro
:aur: https://aur.archlinux.org/

toc::[]

Most of these packages were created because the ones found in the
{aur}[AUR] were horrible. The majority of my packages are built from
the latest developmental branches for both less maintainence burden as
package versions are programmatically generated and for the newest fixes
and bugs, hopefully fixes moreso than bugs ;-).

The style is losely based on
[`man-pages(7)`](http://man7.org/linux/man-pages/man7/man-pages.7.html)
such as using short lowercase descriptions much like a manual synopsis.
Common parameters are grouped together to hopefully make reading the
PKGBUILDs easier.

=== dmenu-pango-imlib

Pango and imlib patches from https://github.com/Cloudef[Cloudef] applied
to dmenu allowing for proper unicode fallback and image generation.

- https://github.com/Cloudef/dmenu-pango-imlib

=== glibc

Removed all non-UTF-8 charmaps allowing for a simplified `locale-gen`
script. Provided an empty `/etc/locales` for users to add their prefered
locale such as _en_GB_. (No charmap, the UTF-8 part is assumed.)

=== system-config

A collection of personal configurations for various machines which
enables installing and managing system configuration as ordinary
packages.
