#!/bin/sh

if [ ! -s /etc/locales ]; then
    printf '/etc/locales: File not found or Empty\n'
    exit 1
fi

while read -r locale; do
    printf 'Generating locale %s...\n' "$locale".UTF-8

    localedef -i "$locale" -f UTF-8 -c "$locale".UTF-8

    case $? in
        4) printf '%s: Invalid locale\n' "$locale" ;;
        *) exit ;;
    esac
done < /etc/locales
